### ISSUE TITLE
Phone Number Change Breaks History UberEats

### ISSUE THREAD

**Issue by HenryTheVacuum** [jonluca/RideShare-Trip-Stats#9]
Hi, 

If your account username/phone number changes the app output graph only displays orders from the current number/username, but if you go into your uber eats history all of the old orders are still there.

If there's a quick fix that would be awesome.

Thanks!

**Comment by flowsion** [comment]
I have changed my phone number numerous times but have not changed my username before. I'm also having issues with the results as **@jessie9212** has stated.

My results are pretty sporadic and seem to capture only the current phone number across a two year period. I'm assuming this is the case, because I've been using UberEats across a few different countries (currencies) and it shows just a small % of the orders in those countries. 

These orders were most likely made prior to me changing the phone number to a local number.

**Comment by jonluca** [comment]
Interesting. I'd need to have access to their API responses to differentiate - my account only has one phone number, so I can't test it. 

If you're familiar with chrome devtools could you create a HAR of you browsing the site? I need to see what the differences in their internal API requests are

**Comment by jonluca** [comment]
Closing as Uber changed their API and uber eats no longer works. Will need to investigate in the future.
